# Generated by Django 5.1.1 on 2024-10-17 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0004_alter_multiimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.product'),
        ),
    ]
