# Generated by Django 5.1.1 on 2024-10-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0005_alter_multiimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiimage',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
