# Generated by Django 5.1.1 on 2024-11-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0009_remove_product_price_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvarient',
            old_name='price',
            new_name='adjusted_price',
        ),
        migrations.AddField(
            model_name='product',
            name='basee_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
