# Generated by Django 5.1.1 on 2024-11-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0010_rename_price_productvarient_adjusted_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvarient',
            name='size',
            field=models.CharField(choices=[('S', 'small'), ('M', 'meduim'), ('L', 'large')], max_length=2),
        ),
    ]
