# Generated by Django 5.1.1 on 2024-11-05 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0011_alter_productvarient_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvarient',
            old_name='adjusted_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='basee_price',
        ),
    ]
