# Generated by Django 5.1.1 on 2024-11-12 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0014_categoryoffer_productoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffer',
            name='Varient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='admin_side.productvarient'),
            preserve_default=False,
        ),
    ]
