# Generated by Django 5.1.1 on 2024-12-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0018_product_sold_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(default=1, upload_to='brands/'),
            preserve_default=False,
        ),
    ]
