# Generated by Django 5.1.1 on 2024-12-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0019_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
