# Generated by Django 5.1.1 on 2024-12-12 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0021_remove_productoffer_varient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='admin_side.product'),
        ),
    ]
