# Generated by Django 5.1.1 on 2024-10-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='products',
            name='delete_status',
        ),
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='products',
            name='title',
        ),
        migrations.RemoveField(
            model_name='products',
            name='updated_at',
        ),
    ]
