# Generated by Django 5.1.1 on 2024-10-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='address',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='landmark',
        ),
        migrations.AddField(
            model_name='addresses',
            name='address1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='addresses',
            name='address2',
            field=models.TextField(null=True),
        ),
    ]
