# Generated by Django 5.1.1 on 2024-11-01 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_orders_user_address'),
        ('userprofile', '0003_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='user_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.addresses'),
        ),
    ]
