# Generated by Django 5.1.1 on 2024-11-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_order_item_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Refund', 'Refund'), ('Dispatch', 'Dispatch'), ('request', 'request')], default='pending', max_length=20),
        ),
    ]
