# Generated by Django 5.1.1 on 2024-11-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_orders_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Refund', 'Refund'), ('Dispatch', 'Dispatch'), ('request', 'request'), ('requestcancelled', 'requestcancelled')], default='pending', max_length=20),
        ),
    ]
