# Generated by Django 5.1.1 on 2024-11-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_orders_cancellation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
