# Generated by Django 5.1.1 on 2024-11-06 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0013_alter_productvarient_products'),
        ('cart', '0015_alter_orders_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='varient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_side.productvarient'),
        ),
    ]
