# Generated by Django 5.1.1 on 2024-11-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_coupons_coupon_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='discount_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
