# Generated by Django 5.1.1 on 2024-11-08 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_wishlistitem_varient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='varient',
        ),
    ]
