# Generated by Django 5.1.1 on 2024-11-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0024_wishlistitem_price_wishlistitem_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
