# Generated by Django 5.1.1 on 2024-11-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0025_alter_wishlistitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Refund', 'Refund'), ('Dispatch', 'Dispatch'), ('CancellationPending', 'CancellationPending'), ('CancellaionDenied', 'cancellaionDenied'), ('Return', 'Return')], default='pending', max_length=20),
        ),
    ]
