# Generated by Django 5.1.1 on 2024-11-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0026_alter_orders_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Refund', 'Refund'), ('Dispatch', 'Dispatch'), ('CancellationPending', 'CancellationPending'), ('CancellaionDenied', 'cancellaionDenied'), ('Return', 'Return')], default='Pending', max_length=20),
        ),
    ]
