# Generated by Django 5.1.1 on 2024-11-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0030_orders_cancellation_requested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Refund', 'Refund'), ('Dispatch', 'Dispatch'), ('Return', 'Return')], default='Pending', max_length=20),
        ),
    ]
