# Generated by Django 5.1.1 on 2024-11-23 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0016_productoffer_description_productoffer_name'),
        ('cart', '0032_alter_orders_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='admin_side.product'),
        ),
    ]
