# Generated by Django 5.1.1 on 2024-11-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0035_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon_usage',
            name='used_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
