# Generated by Django 5.1.1 on 2024-11-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0036_coupon_usage_used_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon_usage',
            name='used_count',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
